version: '3'

services:

  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prd
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  mysql:
    image: mysql:latest
    command: [ "--innodb-use-native-aio=0", "--default-authentication-plugin=mysql_native_password"]
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=nodeuser
      - MYSQL_PASSWORD=nodeuser
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
