FROM nginx:1.15.0-alpine


# apagar a configuracao padrao do nginx
RUN rm -rf /etc/nginx/conf.d/default.conf

# copiar o nosso arquivo de configuracao para o diretorio de configuracao do nginx
COPY nginx.conf /etc/nginx/conf.d/

# criar o arquivo php vazio
RUN mkdir /var/www/html -p && touch /var/www/html/index.php
